name: okj

services:
  db:
    container_name: okj_db
    image: postgres:17.2-alpine3.21
    expose:
      - 5432
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: passwd
      POSTGRES_USER: postgres
    restart: always
    shm_size: 128mb
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 15s
      retries: 3
    networks:
      - okj
    volumes:
      - okj_db:/var/lib/postgresql/data

  otelcol:
    container_name: okj_otelcol
    image: otel/opentelemetry-collector-contrib:0.116.1
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    networks:
      - okj
    volumes:
      - ./configs/otelcol.yaml:/etc/otelcol-contrib/config.yaml

networks:
  okj:
    name: okj

volumes:
  okj_db:
    name: okj_db
