name: okj

services:
  db:
    container_name: okj_db
    image: postgres:17.2-alpine3.21
    expose:
      - 5432
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: passwd
      POSTGRES_USER: postgres
    restart: always
    shm_size: 128mb
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 15s
      retries: 3
    networks:
      - okj
    volumes:
      - okj_db:/var/lib/postgresql/data

  otelcol:
    container_name: okj_otelcol
    image: otel/opentelemetry-collector-contrib:0.116.1
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    networks:
      - okj
    volumes:
      - ../../configs/otel/collector.yaml:/etc/otelcol-contrib/config.yaml

  loki:
    container_name: okj_grafana_loki
    image: grafana/loki:3.3.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - okj

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    container_name: okj_grafana
    image: grafana/grafana:11.4.0
    ports:
      - "3000:3000"
    networks:
      - okj

networks:
  okj:
    name: okj

volumes:
  okj_db:
    name: okj_db
